GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/testing/reset

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"Halle",
    "name":"Allu",
    "password":"12345"
}

###
GET http://localhost:3003/api/blogs